add_executable(Cipher-C++)

target_sources(Cipher-C++
  PRIVATE
    main.cpp
    basics.cpp
    corpus.cpp
    fileLoaders.cpp
    fitness.cpp
    interface.cpp
    modularNumber.cpp
    monoalphabetic.cpp
    periodic.cpp
    polybius.cpp
    solitaire.cpp
    stream.cpp
    strings.cpp
    transpositions.cpp
)